sudo: required

services:
  - docker

language: go
go:
  - tip

before_install:
  - sudo apt-get -qq update
  - mkdir -p ${GOPATH}/bin
  - cd ~
  - curl https://glide.sh/get | sh

install:
  - cd $GOPATH/src/github.com/mh-cbon/gh-api-cli
  - glide install
  - go install

script: echo "pass"

before_deploy:
  - mkdir -p build/{386,amd64}
  - GOOS=linux GOARCH=386 go build --ldflags "-X main.VERSION=${TRAVIS_TAG}" -o build/386/gh-api-cli main.go
  - GOOS=linux GOARCH=amd64 go build --ldflags "-X main.VERSION=${TRAVIS_TAG}" -o build/amd64/gh-api-cli main.go
  - curl -L https://raw.githubusercontent.com/mh-cbon/go-bin-deb/master/create-pkg.sh | GH=mh-cbon/gh-api-cli sh -xe
  - curl -L https://raw.githubusercontent.com/mh-cbon/go-bin-rpm/master/create-pkg.sh | GH=mh-cbon/gh-api-cli sh -xe

after_deploy:
  - curl -L https://raw.githubusercontent.com/mh-cbon/go-bin-deb/master/setup-repository.sh | GH=mh-cbon/gh-api-cli EMAIL=mh-cbon@users.noreply.github.com sh -xe
  - curl -L https://raw.githubusercontent.com/mh-cbon/go-bin-rpm/master/setup-repository.sh | GH=mh-cbon/gh-api-cli EMAIL=mh-cbon@users.noreply.github.com sh -xe


deploy:
  provider: releases
  api_key:
    secure: OFYJ6CyI+zgdt+9uWpve2k+YlHRvWE3wEnAPAAqKkkACzcPpePpjry12gZLU/S2du3vu+4AgE2JiCIsHLTov61tRbyGUCBbCx0q1CkOlNEbhnQcn2vOeXRGIjqOltGordwz6UNyIRCGcAuBWTvgeat6Zem/Lt1lrIFbV7CSGNjtYStFp2Y34m5QC8YFJ/0SH65FdcsUqrL5LFHPakeO+EaWNr/N4WrhYeFUC2o/b4jak4gG415oBlsb6epYvlU8VAXbjQZAfNzBgwlIxgphiiXt0rxOYUNbNb09Yvx7Kcty31HK1GO35xK81iJP+cJ48mawm97IXhoVr72+8liwSEctoef4ipeUcsP/H6yIHAAo6UE8hGZbVNJDh2SbxAhgQOhtYQ80n7nqojiuFz2aXxpV66AinkSA85Gx8PFzhsxGhVjG5VxN/ktmR/+8q3vS6PTuVRuC/d2nHz5Ctij864jzaZvQHZu+KDQAeoSzy/Ojnh1zTbXBK8Zq1xj5B8BkdM7Ry7G0uxS03LfCP9soOqHAo5/eEbI3i7YtmjtoyMEpWCGlwv3S3rvyhHqX3Amdtk+vOfDMANebhNm3Ba7hAZ1cKd7KahoRjMMduHtThjct6YXm7qp7LhR3wwh6SRGNyJBEMqLoxfwn7FRzlluUI4psuOV7kfSyRwgoECEjt7cg=
  file:
    - gh-api-cli-386.deb
    - gh-api-cli-amd64.deb
    - gh-api-cli-386.rpm
    - gh-api-cli-amd64.rpm
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    - secure: AEJAqxCieyKwITRw1TSZjHoit3Hu9I6B06s1gjFSb/t2hAGfac3tbuEVb8JFnPlNDjZ4WB5YIrtrybnq4joO7UMnybtVI/BC8jSeXBWpuU+3T3yUAdjUrTcxv0aJJTIEF8VdiqMFkdSScpD0Ltw+gJ942zdQfGvHNzAp/zhZYel26GmkanIkRGq3O2PwbaRscseRd8Mp3D8B5+YN0pXaHI4v3TllJJZaAA81Swx5J1oC1slrSLNu1Hqh3qF42Ry6HmqrNZti9dyvM2iW1IhuqiWPoKnYn3Z1/8A5wa1ZQoOr9mRMby+bn3PGJDNJg/Ie7pW8zpQyv3ndbZy1YwIJ2a6xYapLSAsrE2alBStL1qgNxDP8P7G+hKB+dY5JlIG+FUSS+/2lMhaoaWt25weFCOPJJgfrrLkB2BuPUWKTJsHDK/XZJlcKSwKiZBpXQ2uwR2atZOjwOiyTKvk5mU5Tu6vDprD/nxuXrMc8mkr26497V5lKcvSW3mF5snJfw/SasHFbdiEele+Xk+qgOh3fzKBq/um8OBzyEz890N6/WmPNwkx2etiq9jXWd6w3HqXokb0aw/f3zF6zgP/qFLlK5G9JIqn7214P94CW0ImzOeLOUTosoq6r8aTl2WCUCtN0DhrZYpL9c1Z6UAHYhYxUHRdG7X6GAu7QY5hrA5ifu0A=
